---
language: ruby

cache:
  - bundler
  - yarn

node_js: "7"

env:
  global:
    - CODECLIMATE_REPO_TOKEN=f5b27b2e25d3f4e199bb2566fb4fd4507144a004c71d4aa33a32c2df5f940333

rvm:
  - 2.3.8

matrix:
  include:
  - env:
      - DISPLAY=':99.0'
      - TESTING_INTERPRETER=yes
    rvm: 2.6.2
    services:
      - xvfb
    addons:
      chrome: stable
    before_install:
      - export CHROMEDRIVER_VERSION=`curl -s http://chromedriver.storage.googleapis.com/LATEST_RELEASE`
      - curl -L -O "http://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
      - unzip chromedriver_linux64.zip && chmod +x chromedriver && sudo mv chromedriver /usr/local/bin
    gemfile: spec/dummy/Gemfile
    script:
      - cd spec/dummy && bundle exec rails test:system
  - rvm: 2.2.10
    before_install:
      - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
      - gem install bundler -v '< 2'
  - env:
      - TESTING_INTERPRETER=yes
    rvm: 2.4.3
    gemfile: gemfiles/rails_5.2.gemfile
  - rvm: 2.3.8
    gemfile: gemfiles/rails_3.2.gemfile
  - rvm: 2.3.8
    gemfile: gemfiles/rails_4.1.gemfile
  - rvm: 2.3.8
    gemfile: gemfiles/rails_4.2.gemfile
  - rvm: 2.6.2
    gemfile: gemfiles/rails_5.0.gemfile
  - rvm: 2.6.2
    gemfile: gemfiles/rails_5.1.gemfile
  - rvm: 2.6.2
    gemfile: gemfiles/rails_5.2.gemfile
  - rvm: 2.6.2
    gemfile: gemfiles/rails_6.0.gemfile
  - rvm: 2.7.0
    gemfile: gemfiles/rails_5.0.gemfile
  - rvm: 2.7.0
    gemfile: gemfiles/rails_5.1.gemfile
  - rvm: 2.7.0
    gemfile: gemfiles/rails_5.2.gemfile
  - rvm: 2.7.0
    gemfile: gemfiles/rails_6.0.gemfile
  - rvm: ruby-head
    gemfile: gemfiles/rails_master.gemfile
  - rvm: 2.6.2
    gemfile: gemfiles/mongoid_7.gemfile
    services:
      - mongodb
  - rvm: 2.6.2
    gemfile: gemfiles/mongoid_6.gemfile
    services:
      - mongodb
  - rvm: 2.6.2
    gemfile: gemfiles/mongoid_5.gemfile
    services:
      - mongodb
  - env: DATABASE=POSTGRESQL
    rvm: 2.6.2
    gemfile: gemfiles/rails_5.2_postgresql.gemfile
    services:
      - postgresql
    before_script:
      - psql -c 'create database graphql_ruby_test;' -U postgres
  - rvm: 2.6.2
    gemfile: Gemfile

jobs:
  allow_failures:
    - rvm: ruby-head
      gemfile: gemfiles/rails_master.gemfile
