---
language: ruby
sudo: false
cache: bundler
env:
  global:
    - CODECLIMATE_REPO_TOKEN=f5b27b2e25d3f4e199bb2566fb4fd4507144a004c71d4aa33a32c2df5f940333
    - JRUBY_OPTS="--debug" # Coverage may be inaccurate without debug flag
before_install:
  - gem update --system --no-doc
  - gem install bundler

rvm:
- 2.1.0 # Lowest version officially supported by that gem
- 2.2.7
- 2.3.4
- 2.4.1
- jruby-9.1.9.0

services:
  - postgresql

before_script:
  - psql -c 'create database graphql_ruby_test;' -U postgres

gemfile:
  - gemfiles/rails_3.2.gemfile
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/without_rails.gemfile


matrix:
  include:
  - env: DATABASE=POSTGRESQL
    gemfile: Gemfile
    rvm: 2.4.1
  - env: WITHOUT_RAILS=yes
    gemfile: gemfiles/without_rails.gemfile
    rvm: 2.4.1

  exclude:
  - rvm: 2.4.1
    gemfile: gemfiles/rails_3.2.gemfile
  - rvm: 2.4.1
    gemfile: gemfiles/rails_4.1.gemfile
  - rvm: 2.4.1
    gemfile: gemfiles/rails_4.2.gemfile
  - rvm: 2.1.0
    gemfile: gemfiles/rails_5.0.gemfile # Rails 5 requires Ruby 2.2.2+
  - rvm: jruby-9.1.9.0
    gemfile: gemfiles/rails_5.0.gemfile # Rails 5 is not supported atm
  - rvm: 2.1.0
    gemfile: gemfiles/rails_5.1.gemfile # Rails 5 requires Ruby 2.2.2+
  - rvm: jruby-9.1.9.0
    gemfile: gemfiles/rails_5.1.gemfile # Rails 5 is not supported atm
