---
language: ruby
sudo: false
cache:
  - bundler
  - yarn
node_js: "7"

env:
  global:
    - CODECLIMATE_REPO_TOKEN=f5b27b2e25d3f4e199bb2566fb4fd4507144a004c71d4aa33a32c2df5f940333
before_install:
  - gem update --system --no-doc
  - gem install bundler

rvm:
- 2.2.8 # Lowest version officially supported by the gem is 2.2
- 2.4.3

services:
  - postgresql
  - mongodb

before_script:
  - psql -c 'create database graphql_ruby_test;' -U postgres

gemfile:
  - gemfiles/rails_3.2.gemfile
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile


matrix:
  include:
  - env:
      - SYSTEM_TESTS=yes
      - DISPLAY=':99.0'
    gemfile: gemfiles/rails_5.1.gemfile
    rvm: 2.4.3
    addons:
      apt:
        sources:
          - google-chrome
        packages:
          - google-chrome-stable
    before_install:
      - export CHROMEDRIVER_VERSION=`curl -s http://chromedriver.storage.googleapis.com/LATEST_RELEASE`
      - curl -L -O "http://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
      - unzip chromedriver_linux64.zip && chmod +x chromedriver && sudo mv chromedriver /usr/local/bin
    before_script:
      - sh -e /etc/init.d/xvfb start
  - env: DATABASE=POSTGRESQL
    gemfile: gemfiles/rails_5.1.gemfile
    rvm: 2.4.3
  - env: WITHOUT_RAILS=yes
    gemfile: gemfiles/without_rails.gemfile
    rvm: 2.4.3

  exclude:
  - rvm: 2.4.3
    gemfile: gemfiles/rails_3.2.gemfile
  - rvm: 2.4.3
    gemfile: gemfiles/rails_4.1.gemfile
  - rvm: 2.4.3
    gemfile: gemfiles/rails_4.2.gemfile
  - rvm: 2.2.8
    gemfile: gemfiles/rails_5.0.gemfile
  - rvm: 2.2.8
    gemfile: gemfiles/rails_5.1.gemfile
  - rvm: 2.2.8
    gemfile: gemfiles/rails_5.2.gemfile
